name: Update Activity

on:
  schedule:
    # Runs at 12:00 am midnight IST every day
    - cron: '30 18 * * *'

jobs:
  update_activity:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update activity file
      run: echo "Activity update for $(date)" >> ./content/activity.txt

    - name: Commit changes
      run: |
        git config --local user.name "arjunvtsuresh"
        git config --local user.email "arjunvtsuresh@gmail.com"
        git add ./content/activity.txt
        git commit -m "Update activity"
        git push -u origin main

